# Generated by Django 4.2.1 on 2023-06-17 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del grupo')),
                ('user_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
                ('users_list', models.ManyToManyField(related_name='user_in_groups', to=settings.AUTH_USER_MODEL, verbose_name='Listado de usuarios')),
            ],
        ),
    ]
