# Generated by Django 4.2.1 on 2023-06-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la rutina')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='group.group', verbose_name='Grupo')),
            ],
            options={
                'unique_together': {('name', 'group')},
            },
        ),
    ]
